@BASE_URL = http://localhost:3500/

GET {{BASE_URL}}
###

POST {{BASE_URL}}
Content-Type: application/json

{
    "name": "Elmar",
    "sname": "Amanov"
}


###
POST {{BASE_URL}}
Content-Type: application/x-www-form-urlencoded

name="Elmar"&sname="Alibeyli"


###
//URL Parametresi 
GET {{BASE_URL}}12?sortbyName=name




/////////////////////////////////////// USER API //////////////////////////////
###
//user request
@USER_API = http://localhost:3500/api

//Butun Userler
GET {{USER_API}}/users/


//user id sine gore isdek
###
GET {{USER_API}}/users/628b78351d90fc6c088287f2

//yeni user yaratmaq => Post request
###
POST  {{USER_API}}/users/
Content-Type: application/json

{
    "name": "El",
    "userName": "elmar12",
    "email": "elmar.amanov1120@gmail.com",
    "password": "eldar12312"
}


###
PATCH   {{USER_API}}/users/628c04d7baab76a8efc4188d
Content-Type: application/json

{
    "email": "elsvs",
    "password": "elda.amanov1120@gmail.com"
}


###
DELETE    {{USER_API}}/users/628b78351d90fc6c088287f2
Content-Type: application/json




